/*
 * Copyright 2024 Benjamin Dittwald
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 *
 *  * Copyright 2024 Benjamin Dittwald
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */

/*
 *
 *  * Copyright 2024 Benjamin Dittwald
 *  *
 *  * Licensed under the Apache License, Version 2.0 (the "License");
 *  * you may not use this file except in compliance with the License.
 *  * You may obtain a copy of the License at
 *  *
 *  *     http://www.apache.org/licenses/LICENSE-2.0
 *  *
 *  * Unless required by applicable law or agreed to in writing, software
 *  * distributed under the License is distributed on an "AS IS" BASIS,
 *  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  * See the License for the specific language governing permissions and
 *  * limitations under the License.
 *
 */

/*
 * Copyright 2024 Benjamin Dittwald
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

-- MOVIE

CREATE TABLE genres_number_mapping
(
    number_id BIGINT  NOT NULL,
    genres    VARCHAR(255),
    genres_id INTEGER NOT NULL,
    CONSTRAINT pk_genres_number_mapping PRIMARY KEY (number_id, genres_id)
);

CREATE TABLE movies
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid         UUID                                    NOT NULL,
    version      BIGINT,
    tmdb_id      INTEGER,
    release_year INTEGER,
    imdb_id      VARCHAR(50),
    CONSTRAINT pk_movies PRIMARY KEY (id)
);

ALTER TABLE movies
    ADD CONSTRAINT uc_movies_uuid UNIQUE (uuid);

ALTER TABLE genres_number_mapping
    ADD CONSTRAINT fk_genres_number_mapping_on_movie FOREIGN KEY (number_id) REFERENCES movies (id);

-- LOCALIZED MOVIE

CREATE TABLE localized_movie
(
    title      VARCHAR(255),
    overview   OID,
    tagline    VARCHAR(255),
    poster_url VARCHAR(255),
    id         BIGINT       NOT NULL,
    locale     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_localizedmovie PRIMARY KEY (id, locale)
);

ALTER TABLE localized_movie
    ADD CONSTRAINT FK_LOCALIZEDMOVIE_ON_ID FOREIGN KEY (id) REFERENCES movies (id);

-- SCENE

CREATE TABLE scenes
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid     UUID                                    NOT NULL,
    lon      DOUBLE PRECISION                        NOT NULL,
    lat      DOUBLE PRECISION                        NOT NULL,
    version  BIGINT,
    movie_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_scenes PRIMARY KEY (id)
);

ALTER TABLE scenes
    ADD CONSTRAINT uc_scenes_uuid UNIQUE (uuid);

ALTER TABLE scenes
    ADD CONSTRAINT FK_SCENES_ON_MOVIE FOREIGN KEY (movie_id) REFERENCES movies (id);

-- LOCALIZED SCENE

CREATE TABLE localized_scene
(
    description OID,
    id          BIGINT       NOT NULL,
    locale      VARCHAR(255) NOT NULL,
    CONSTRAINT pk_localizedscene PRIMARY KEY (id, locale)
);

ALTER TABLE localized_scene
    ADD CONSTRAINT FK_LOCALIZEDSCENE_ON_ID FOREIGN KEY (id) REFERENCES scenes (id);
